services:
  caddy:
    image: lahiru98s/caddy-extended
    container_name: edge_caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - wp_net

volumes:
  caddy_data:
  caddy_config:

networks:
  wp_net:
    external: true
